version: '3'

services:
  db:
    build: ./postgres/
    container_name: db
    networks:
        - default
  web:
    build: .
    container_name: web
    #command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && uwsgi --ini test_uwsgi.ini"
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && uwsgi --ini test_uwsgi.ini"
    volumes:
      - .:/code
    #ports:
      #- "8001:80"
    expose:
      - "3000"
    depends_on:
      - db
    networks:
        - default
  corn:
     build: ./selenium_driver_chrome/
     command: bash -c "python test.py && python test2.py"
     volumes:
      - .:/code
     ports:
      - "8002:8002"
     depends_on:
      - db
      - web
     networks:
      - default

  nginx:
    build: ./nginx/
    container_name: nginx
    restart: always
    ports:
      - "8003:80"
    #command : bash -c "sudo /etc/init.d/nginx reload && sudo /etc/init.d/nginx restart"
    command : bash -c " sudo /etc/init.d/nginx reload && exec nginx -g 'daemon off;' "
    volumes:
      - .:/code
    depends_on:
      - web
    links:
      - web:web
    networks:
        - default
networks:
  default:          
